var hierarchy =
[
    [ "signal_spectrum_utility.i18n._TranslationKeys", "classsignal__spectrum__utility_1_1i18n_1_1__TranslationKeys.html", null ],
    [ "signal_spectrum_utility.config.AppSettings", "classsignal__spectrum__utility_1_1config_1_1AppSettings.html", null ],
    [ "signal_spectrum_utility.ui_components.ChartsPanelCallbacks", "classsignal__spectrum__utility_1_1ui__components_1_1ChartsPanelCallbacks.html", null ],
    [ "signal_spectrum_utility.ui_components.ChartsPanelView", "classsignal__spectrum__utility_1_1ui__components_1_1ChartsPanelView.html", null ],
    [ "signal_spectrum_utility.types.FrequencyRange", "classsignal__spectrum__utility_1_1types_1_1FrequencyRange.html", null ],
    [ "signal_spectrum_utility.config.GlobalSettings", "classsignal__spectrum__utility_1_1config_1_1GlobalSettings.html", null ],
    [ "signal_spectrum_utility.io.LoadedSensorFile", "classsignal__spectrum__utility_1_1io_1_1LoadedSensorFile.html", null ],
    [ "signal_spectrum_utility.interaction_controllers.ManualMarkerCallbacks", "classsignal__spectrum__utility_1_1interaction__controllers_1_1ManualMarkerCallbacks.html", null ],
    [ "signal_spectrum_utility.interaction_controllers.ManualWindowMarkerController", "classsignal__spectrum__utility_1_1interaction__controllers_1_1ManualWindowMarkerController.html", null ],
    [ "signal_spectrum_utility.metrics_tables_controller.MetricsTablesController", "classsignal__spectrum__utility_1_1metrics__tables__controller_1_1MetricsTablesController.html", null ],
    [ "signal_spectrum_utility.ui_components.OffsetStackCallbacks", "classsignal__spectrum__utility_1_1ui__components_1_1OffsetStackCallbacks.html", null ],
    [ "signal_spectrum_utility.ui_components.OffsetStackSectionView", "classsignal__spectrum__utility_1_1ui__components_1_1OffsetStackSectionView.html", null ],
    [ "signal_spectrum_utility.types.PairwiseComparison", "classsignal__spectrum__utility_1_1types_1_1PairwiseComparison.html", null ],
    [ "signal_spectrum_utility.types.RangeMetrics", "classsignal__spectrum__utility_1_1types_1_1RangeMetrics.html", null ],
    [ "generate_sensor_data.generators.scenarios.ScenarioBundle", "classgenerate__sensor__data_1_1generators_1_1scenarios_1_1ScenarioBundle.html", null ],
    [ "signal_spectrum_utility.ui_components.SegmentationCallbacks", "classsignal__spectrum__utility_1_1ui__components_1_1SegmentationCallbacks.html", null ],
    [ "signal_spectrum_utility.async_recompute.SegmentationJobInput", "classsignal__spectrum__utility_1_1async__recompute_1_1SegmentationJobInput.html", null ],
    [ "signal_spectrum_utility.async_recompute.SegmentationJobResult", "classsignal__spectrum__utility_1_1async__recompute_1_1SegmentationJobResult.html", null ],
    [ "signal_spectrum_utility.ui_components.SegmentationSectionView", "classsignal__spectrum__utility_1_1ui__components_1_1SegmentationSectionView.html", null ],
    [ "signal_spectrum_utility.config.SegmentationSettings", "classsignal__spectrum__utility_1_1config_1_1SegmentationSettings.html", null ],
    [ "signal_spectrum_utility.ui_components.SelectionOrderCallbacks", "classsignal__spectrum__utility_1_1ui__components_1_1SelectionOrderCallbacks.html", null ],
    [ "signal_spectrum_utility.ui_components.SelectionOrderSectionView", "classsignal__spectrum__utility_1_1ui__components_1_1SelectionOrderSectionView.html", null ],
    [ "signal_spectrum_utility.ui_components.SelectorPanelCallbacks", "classsignal__spectrum__utility_1_1ui__components_1_1SelectorPanelCallbacks.html", null ],
    [ "signal_spectrum_utility.ui_components.SelectorPanelView", "classsignal__spectrum__utility_1_1ui__components_1_1SelectorPanelView.html", null ],
    [ "signal_spectrum_utility.types.SensorChannel", "classsignal__spectrum__utility_1_1types_1_1SensorChannel.html", null ],
    [ "signal_spectrum_utility.session.SessionState", "classsignal__spectrum__utility_1_1session_1_1SessionState.html", null ],
    [ "signal_spectrum_utility.interaction_controllers.SignalCrosshairCallbacks", "classsignal__spectrum__utility_1_1interaction__controllers_1_1SignalCrosshairCallbacks.html", null ],
    [ "signal_spectrum_utility.interaction_controllers.SignalCrosshairController", "classsignal__spectrum__utility_1_1interaction__controllers_1_1SignalCrosshairController.html", null ],
    [ "signal_spectrum_utility.config.SignalSettings", "classsignal__spectrum__utility_1_1config_1_1SignalSettings.html", null ],
    [ "signal_spectrum_utility.async_recompute.SpectrumJobInput", "classsignal__spectrum__utility_1_1async__recompute_1_1SpectrumJobInput.html", null ],
    [ "signal_spectrum_utility.async_recompute.SpectrumJobResult", "classsignal__spectrum__utility_1_1async__recompute_1_1SpectrumJobResult.html", null ],
    [ "signal_spectrum_utility.async_recompute.SpectrumPlotSeries", "classsignal__spectrum__utility_1_1async__recompute_1_1SpectrumPlotSeries.html", null ],
    [ "signal_spectrum_utility.ui_components.SpectrumRangeCallbacks", "classsignal__spectrum__utility_1_1ui__components_1_1SpectrumRangeCallbacks.html", null ],
    [ "signal_spectrum_utility.interaction_controllers.SpectrumRangeDrawCallbacks", "classsignal__spectrum__utility_1_1interaction__controllers_1_1SpectrumRangeDrawCallbacks.html", null ],
    [ "signal_spectrum_utility.interaction_controllers.SpectrumRangeDrawController", "classsignal__spectrum__utility_1_1interaction__controllers_1_1SpectrumRangeDrawController.html", null ],
    [ "signal_spectrum_utility.ui_components.SpectrumRangeSectionView", "classsignal__spectrum__utility_1_1ui__components_1_1SpectrumRangeSectionView.html", null ],
    [ "signal_spectrum_utility.types.SpectrumResult", "classsignal__spectrum__utility_1_1types_1_1SpectrumResult.html", null ],
    [ "signal_spectrum_utility.config.SpectrumSettings", "classsignal__spectrum__utility_1_1config_1_1SpectrumSettings.html", null ],
    [ "signal_spectrum_utility.async_recompute.SpectrumSignalInput", "classsignal__spectrum__utility_1_1async__recompute_1_1SpectrumSignalInput.html", null ],
    [ "generate_sensor_data.utils.validator.ValidationResult", "classgenerate__sensor__data_1_1utils_1_1validator_1_1ValidationResult.html", null ],
    [ "signal_spectrum_utility.types.WindowSegment", "classsignal__spectrum__utility_1_1types_1_1WindowSegment.html", null ],
    [ "QDialog", null, [
      [ "signal_spectrum_utility.settings_dialog.SettingsDialog", "classsignal__spectrum__utility_1_1settings__dialog_1_1SettingsDialog.html", null ]
    ] ],
    [ "QMainWindow", null, [
      [ "signal_spectrum_utility.app.MainWindow", "classsignal__spectrum__utility_1_1app_1_1MainWindow.html", null ]
    ] ]
];